name: ZMK Firmware
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */2 *'  # run every two months to keep artifacts from expiring
jobs:
  store-keymap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Rename keymap file
        run: |
          # Ensure we're using only the Colemak keymap
          cp ${{ github.workspace }}/config/charybdis.keymap ${{ github.workspace }}/config/colemak_dh.keymap
      - uses: actions/upload-artifact@v4
        with:
          name: keymap_files
          path: ${{ github.workspace }}/config/*.keymap
  build:
    needs: store-keymap
    uses: ./.github/workflows/user_config_build.yaml
  keymap_images:
    needs: build
    permissions:
      contents: write
    uses: ./.github/workflows/draw_keymaps.yaml
